#   _                       _ _
#  | |                     (_) |
#  | | __ _ _____   _  __ _ _| |_
#  | |/ _` |_  / | | |/ _` | | __|
#  | | (_| |/ /| |_| | (_| | | |_
#  |_|\__,_/___|\__, |\__, |_|\__|
#                __/ | __/ |
#               |___/ |___/
fontFamily: "SF Symbols"
gui:
  showIcons: true
  showRandomTip: false
  showBottomLine: false
  nerdFontsVersion: '3'
  border: 'single'
git:
  log:
    showGraph: 'always'
  parseEmoji: true
  pagers:
    - pager: delta --dark --paging=never
      useConfig: false
customCommands:
  - key: 'C'
    command: 'clear && git cz c'
    description: 'Commit with commitizen'
    context: 'files'
    loadingText: 'opening commitizen commit tool'
    output: terminal
  - key: '<c-s>'
    command: 'git save'
    description: 'Create savepoint commit'
    context: 'files'
  - key: 'u'
    command: 'git undo'
    description: 'Undo last commit'
    context: 'files'
  - key: 'u'
    command: 'git undo'
    description: 'Undo last commit'
    context: 'commits'
  - key: '<c-v>'
    context: 'global'
    description: 'Create a new conventional commit'
    loadingText: 'Creating conventional commit...'
    command: "git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{ .Form.Scope }}){{ end }}{{.Form.Breaking}}: {{.Form.Message}}'"
    prompts:
      - type: 'menu'
        key: 'Type'
        title: '选择您要提交的更改类型'
        options:
          - name: 'fix'
            description: '错误修复。与语义版本控制中的PATCH相关'
            value: 'fix'
          - name: 'feat'
            description: '新功能。与语义版本控制中的次版本MINOR相关'
            value: 'feat'
          - name: 'docs'
            description: '仅文档变更'
            value: 'docs'
          - name: 'style'
            description: '不影响代码逻辑的更改'
            value: 'style'
          - name: 'refactor'
            description: '重构。既不修复错误也不添加功能的代码更改'
            value: 'refactor'
          - name: 'perf'
            description: '提高性能的代码更改'
            value: 'perf'
          - name: 'test'
            description: '测试。添加缺失的测试或纠正现有的测试'
            value: 'test'
          - name: 'build'
            description: '影响构建系统或外部依赖关系的更改'
            value: 'build'
          - name: 'ci'
            description: 'CI配置文件和脚本的更改'
            value: 'ci'
          - name: 'chore'
            description: "其他不修改src或测试文件的更改"
            value: 'chore'
          - name: 'revert'
            description: '撤销还原之前的提交'
            value: 'revert'
      - type: 'input'
        title: '影响范围? (可选)'
        key: 'Scope'
        initialValue: ''
      - type: 'input'
        title: '撰写代码更改的简要说明'
        key: 'Message'
        initialValue: ''
      - type: 'menu'
        key: 'Breaking'
        title: '这是否是一个破坏性更新（BREAKING CHANGE）？与语义版本控制中的主要版本相关'
        options:
          - name: 'no'
            value: ''
          - name: 'yes'
            value: '!'
      - type: 'confirm'
        key: 'Confirm'
        title: 'Commit'
        body: '确认进行提交?'
